const D=window.TF_DATA;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=u=>esc(D.assets[u]||u||'');
const A=D.articles, C=Object.fromEntries(D.competitions.map(c=>[c.id,c.label_fr])), G=Object.fromEntries(D.genres.map(g=>[g.id,g.label_fr]));
const hero=A.find(a=>a.featured)||A[0]||{title:"Les articles sont momentanément indisponibles",deck:"Retrouvez toutes nos publications dans les archives.",slug:"",hero_image:"",id:""};
const hasDailyPoster=document.body.dataset.style==='club';
const dailyPlayerImage=hasDailyPoster?'/home/assets/joueur-mystere-silhouette.png':'/home/assets/player-silhouette.svg';
const site=location.origin, yt='https://www.youtube.com/@Tomso-Foot', tw='https://www.twitch.tv/tomsofoot', mag=site+'/magazine/lecteur.html';
const icons={arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',home:'<path d="m3 11 9-8 9 8M5 10v11h14V10M10 21v-7h4v7"/>',game:'<rect x="2" y="6" width="20" height="13" rx="5"/><path d="M6 12h5M8.5 9.5v5M16 10h.1M18 14h.1"/>',book:'<path d="M12 5c-3-2-6-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1ZM12 5v15"/>',live:'<circle cx="12" cy="12" r="2"/><path d="M7 7a7 7 0 0 0 0 10M17 7a7 7 0 0 1 0 10M4 4a11 11 0 0 0 0 16M20 4a11 11 0 0 1 0 16"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/>',tablet:'<rect x="3" y="2" width="18" height="20" rx="2"/><path d="M10 18h4"/>',desktop:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M12 17v4M7 21h10"/>',play:'<path d="m9 5 11 7-11 7Z"/>',shirt:'<path d="m8 3 4 2 4-2 6 5-4 4-2-2v11H8V10l-2 2-4-4Z"/>',globe:'<circle cx="12" cy="12" r="10"/><ellipse cx="12" cy="12" rx="4" ry="10"/><path d="M2 12h20"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 2v6M16 2v6M3 10h18M7 14h3M14 14h3M7 17h3"/>',trophy:'<path d="M7 3h10v6c0 7-10 7-10 0ZM12 14v7M7 21h10M7 5H3v3c0 4 4 4 4 4M17 5h4v3c0 4-4 4-4 4"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.arrow}</svg>`;
const link=(url,label,cls='')=>`<a href="${esc(url)}" class="${cls}">${label}</a>`;
const tag=a=>[C[a.competition_id],G[a.genre_id]].filter(Boolean).join(' · ');
const meta=a=>{const value=a.published_at||a.created_at,date=value?new Date(value):null;return [date&&Number.isFinite(date.getTime())?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Paris'}).format(date):'',Number(a.reading_time)>0?a.reading_time+' min de lecture':''].filter(Boolean).join(' · ');};
const story=(a,cls='')=>`<a class="story ${cls}" href="${site}/articles/${esc(a.slug)}"><div class="story-image"><img loading="lazy" decoding="async" src="${asset(a.hero_image)}" alt="${esc(a.hero_alt||a.title)}"><span class="round-arrow">↗</span></div><div class="story-copy"><span class="eyebrow">${esc(tag(a))}</span><h3>${esc(a.title.trim())}</h3><p class="meta">${esc(meta(a))}${hasDailyPoster?`<span class="story-views" data-article-views="${esc(a.id)}" hidden></span>`:""}</p></div></a>`;
const navLinks=()=>[['#derniers-articles','Actualités'],[site+'/articles/','Articles'],[mag,'Magazine'],['#videos','Vidéos'],['#formats','Jeu'],['#newsletter','Newsletter'],[yt,'YouTube ↗']].map(x=>link(...x)).join('');
const modes=()=>`<div class="reading-picker" role="group" aria-label="Mode de lecture"><span>Mode de lecture</span>${[['smartphone','phone','Smartphone'],['tablet','tablet','Tablette'],['desktop','desktop','Ordinateur']].map(([v,i,l])=>`<button class="reading-mode" data-mode="${v}" aria-label="Lecture ${l}" title="${l}" aria-pressed="false">${icon(i)}</button>`).join('')}</div>`;
const logo=`<img class="tf-brand-mark" src="/assets/brand/logotf4.png" width="48" height="48" alt=""><span class="tf-brand-name">TomsoFoot</span>`;
const footnav=()=>[['#','home','Accueil'],['#formats','game','Le jeu'],[mag,'book','Le mag'],[tw,'live','Live']].map(([url,i,label])=>link(url,icon(i)+`<span>${label}</span>`)).join('');
const rubrics=[['Championnats',['Ligue 1','Premier League','Liga','Serie A','Bundesliga']],['Clubs',['Ligue des champions','Europa League','Conference League']],['Sélections',['Coupe du monde','Euro','Ligue des Nations']]];
const hints=D.hints;
// Même présentation que 2a-03 : une fourchette, jamais un âge exact déduit de la seule année.
const hintYear=Number(String(hints.for||'').slice(0,4)),birthYear=Number(hints.birthYear);
const ageRange=Number.isInteger(hintYear)&&Number.isInteger(birthYear)&&birthYear>0&&hintYear>birthYear&&hintYear-birthYear<120?`${hintYear-birthYear-1}–${hintYear-birthYear} ans`:'—';
const hintItems=[['shirt','Poste',hints.position],['globe','Nationalité',hints.country],['calendar','Âge',ageRange],['trophy','Championnats',hints.league]];
document.querySelector('#app').innerHTML=`
<a class="skip" href="#main">Aller au contenu</a>
<div class="announcement" id="cms-bandeau">Le numéro 12 est en ligne <span>·</span> Argentine–Angleterre, le match qui n'a jamais pris fin</div>
<header class="site-header"><div class="header-main shell"><a class="logo tf-brand" href="#">${logo}</a><p class="tagline">Le football, raconté autrement.</p>${modes()}<button class="menu-btn" aria-expanded="false" aria-controls="menu-panel" aria-label="Ouvrir le menu">${icon('menu')}<span>Menu</span></button></div><nav class="desktop-nav shell" aria-label="Navigation principale">${navLinks()}</nav><div class="menu-panel shell" id="menu-panel" hidden><nav>${navLinks()}</nav>${modes()}</div></header>
<nav class="mobile-tabs" aria-label="Sections mobiles">${footnav()}</nav>
<main id="main">
<aside class="now-rail shell" aria-label="TomsoFoot maintenant"><strong><i></i> TomsoFoot maintenant</strong><div class="rail-viewport"><div class="rail-track"><a href="${site}/articles/${esc(A[0]?.slug||'')}"><b>Nouveau</b> ${esc(A[0]?.title||'Les publications TomsoFoot')}</a><span id="next-match"></span><span>Nouveau joueur dans <time data-countdown>—</time></span></div></div><button class="rail-pause" aria-label="Mettre le bandeau en pause" aria-pressed="false">Ⅱ</button></aside>
<section class="hero shell" id="hero-une"><div class="hero-visual"><img fetchpriority="high" decoding="async" src="${asset(hero.hero_image)}" alt="${esc(hero.hero_alt||hero.title)}"></div><div class="hero-inner" id="hero-inner"><div class="eyebrow" id="hero-kicker">${esc(tag(hero))}</div><h1 id="hero-title">${esc(hero.title.trim())}</h1><p class="hero-deck" id="hero-deck">${esc(hero.deck)}</p><p class="hero-meta" id="hero-meta">${esc(meta(hero))}</p><div class="cta-row"><a id="hero-cta" class="button primary" href="${site}/articles/${esc(hero.slug)}">Lire l'article ${icon('arrow')}</a><a class="button ghost" href="${site}/articles/">Toutes les publications</a></div></div><span class="hero-label">À LA UNE</span></section>
<nav class="rubrics shell" aria-label="Compétitions">${rubrics.map(([title,items])=>`<div class="rgroup"><h2>${title}</h2><div>${items.map(l=>`<a href="#archives" data-rubric="${esc(l)}">${l}</a>`).join('')}</div></div>`).join('')}</nav>
<section class="section match-section shell" id="match-center"><div class="section-head"><div><span class="kicker">À suivre</span><h2>Les prochains rendez-vous football</h2></div><div class="controls" id="mc-ctrl"><button data-match-prev aria-label="Matchs précédents">←</button><button data-match-next aria-label="Matchs suivants">→</button></div></div><div class="match-grid" id="mc-stage" aria-live="off"></div><div class="carousel-foot"><div class="dots" id="mc-dots"></div><span>Rotation toutes les 10 s</span><button class="text-button" id="match-pause" aria-pressed="false">Pause</button></div></section>
<section class="section experiences shell" id="formats"><div class="section-head"><div><span class="kicker">Une marque, trois expériences</span><h2>Choisissez votre terrain</h2></div><span class="section-note">Les articles, les vidéos, les jeux.</span></div><div class="experience-grid">
<article class="daily${hasDailyPoster?' daily-poster':''}"><span class="kicker">${icon('game')} Jogadle · Le défi quotidien</span><h3>Le joueur<br>du jour</h3><p>Trouvez le footballeur mystère</p><img class="mystery-player" src="${dailyPlayerImage}" alt="Silhouette du joueur mystère"><div class="daily-bottom"><p class="hint-caption">Indices du joueur de la veille</p><div class="hints">${hintItems.map(([i,l,v])=>`<div>${icon(i)}<span>${l}</span><strong>${esc(v||'—')}</strong></div>`).join('')}</div><div class="daily-action"><div><span>Nouveau joueur dans</span><time id="tsf-clk" data-countdown>—</time></div><button class="button primary" data-open-game-choice>Jouer maintenant ${icon('arrow')}</button></div></div></article>
<article class="live-card"><img src="/home/assets/live-background.png" alt="Le live TomsoFoot"><div class="live-copy"><span class="live-badge ${D.twitch.live?'on':''}" id="tsf-live">${D.twitch.live?'● En direct':'Twitch'}</span><h3>Le live<br>TomsoFoot</h3><p>Débats, matchs et passion football</p><a class="button white" href="${tw}">Regarder le live ${icon('arrow')}</a></div></article>
<article class="feature youtube"><div class="feature-image"><img src="/home/assets/coup-envoi.png" alt="Coup d'envoi, chaîne YouTube TomsoFoot"></div><div class="feature-copy"><span class="kicker">La chaîne YouTube</span><h3>Coup d'envoi</h3><a href="${yt}">Voir la chaîne ${icon('arrow')}</a></div></article>
<article class="feature career" id="mode-carriere"><div class="feature-image"><img src="/home/assets/manager-reference.jpg" alt="Visuel du Mode Carrière TomsoFoot"></div><div class="feature-copy"><span class="kicker">Le second jeu TomsoFoot</span><h3>Mode Carrière</h3><a href="${site}/mode-carriere/">Découvrir le jeu ${icon('arrow')}</a></div></article>
<article class="feature films"><div class="feature-image"><img src="${asset((D.docs.videos[0]?.thumbnail||''))}" alt="${esc((D.docs.videos[0]?.title||'Les documentaires'))}"></div><div class="feature-copy"><span class="kicker">Histoires de football</span><h3>Les documentaires</h3><a href="#videos">Découvrir les films ${icon('arrow')}</a></div></article>
</div></section>
<section class="section latest shell" id="derniers-articles"><div class="section-head"><div><span class="kicker">Le fil</span><h2>Derniers articles</h2></div><a class="see-all" href="${site}/articles/">Tous les articles ${icon('arrow')}</a></div><div class="latest-grid" id="latest-articles">${A.slice(0,3).map(a=>story(a)).join('')}</div></section>
<section class="section archive-section shell" id="archives"><div class="section-head"><div><span class="kicker">Les archives</span><h2>Parcourir par compétition</h2></div></div><nav class="archive-filters" aria-label="Filtrer les archives" id="arch-chips"></nav><div class="archive-grid" id="arch-out" aria-live="polite"></div><a class="button outline archive-all" href="${site}/articles/">Voir toutes les archives ${icon('arrow')}</a></section>
<section class="section docs-section" id="videos"><div class="shell"><div class="section-head"><div><span class="kicker">La chaîne</span><h2>Les documentaires</h2></div><a class="see-all" href="${yt}">Voir la chaîne ${icon('arrow')}</a></div><div id="docs-root"></div></div></section>
<section class="newsletter shell" id="newsletter"><div><span class="kicker">Le vestiaire TomsoFoot</span><h2>Une longueur<br>d'avance.</h2></div><form class="newsletter-form"><label for="email">Votre adresse e-mail</label><div><input id="email" name="email" type="email" placeholder="vous@exemple.fr" required><button class="button white" type="submit">S'inscrire ${icon('arrow')}</button></div><p id="newsletter-status" role="status"></p></form></section>
<section class="manifesto section shell" id="vision"><span class="kicker">${esc(D.local.manifeste.numero)}</span><div><blockquote>Le score raconte le résultat.<br><em>Nous racontons ce qu'il signifie.</em></blockquote><p>${esc(D.local.manifeste.texte)}</p><a class="button outline" href="${mag}">Découvrir notre vision ${icon('arrow')}</a></div></section>
</main><footer><div class="shell"><div class="footer-top"><div><a class="logo tf-brand" href="#">${logo}</a><p>Le football, notre passion.</p></div><nav aria-label="Liens de pied de page">${[[yt,'YouTube ↗'],['https://www.instagram.com/tomso_foot/','Instagram ↗'],['https://x.com/tomsofoot','X ↗'],['https://www.tiktok.com/@tomsofoot','TikTok ↗'],['mailto:tomsofoot@gmail.com','Contact'],[mag,'Le magazine'],[site+'/jeu','Jogadle'],[site+'/mentions-legales','Mentions légales'],[site+'/confidentialite','Confidentialité'],[site+'/regie','Régie']].map(x=>link(...x)).join('')}</nav></div><div class="footer-bottom"><div class="rub-stats">Consultations du jour <span>· YouTube <b data-count="youtube">${D.views.youtube??'—'}</b></span><span>· Magazine <b data-count="magazine">${D.views.magazine??'—'}</b></span><span>· Jeux <b data-count="jeux">${D.views.jeux??'—'}</b></span></div><span>© 2026 TomsoFoot</span></div></div></footer>
<nav class="bottom-nav" aria-label="Navigation mobile fixe">${footnav()}</nav>
<dialog id="game-choice" aria-labelledby="game-choice-title"><button class="dialog-close" aria-label="Fermer le choix des jeux">×</button><span class="kicker">Les jeux TomsoFoot</span><h2 id="game-choice-title">Choisissez votre défi</h2><div class="game-options"><a href="${site}/jeu"><img src="${dailyPlayerImage}" alt=""><h3>Jogadle</h3><p>Le joueur du jour</p><span class="button primary">Jouer maintenant →</span></a><a href="${site}/mode-carriere/"><img src="/home/assets/manager-reference.jpg" alt="Mode Carrière"><h3>Mode Carrière</h3><p>Le second jeu TomsoFoot</p><span class="button primary">Jouer maintenant →</span></a></div></dialog>`;
function countdown(){let now=window.TF_CAPTURE?new Date(D.capturedAt):new Date();let p=new Date(now.toLocaleString('en-US',{timeZone:'Europe/Paris'})),n=new Date(p);n.setHours(24,0,0,0);let s=Math.floor((n-p)/1000),t=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(n=>String(n).padStart(2,'0')).join(':');document.querySelectorAll('[data-countdown]').forEach(el=>el.textContent=t)}countdown();setInterval(countdown,1000);
const matches=(D.matches.matches||[]).filter(m=>hasDailyPoster||!['FT','AET','PEN'].includes(m.status));let matchFeedState='loading';let mi=0,matchPaused=false,matchModalOpen=false;const per=()=>document.querySelector('#mc-stage').clientWidth<700?1:3;
function matchDay(m){if(!hasDailyPoster)return m.day==='tomorrow'?'Demain':"Aujourd'hui";try{const format=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'});const delta=(Date.parse(format.format(new Date(m.ts)))-Date.parse(format.format(new Date())))/86400000;return delta===0?"Aujourd’hui":delta===1?'Demain':delta===-1?'Hier':new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',day:'numeric',month:'short'}).format(new Date(m.ts));}catch{return'';}}
function matchCard(m){let live=['1H','HT','2H','ET','P','LIVE','BT'].includes(m.status),finished=['FT','AET','PEN'].includes(m.status);let center=live||finished?(m.gh??'—')+' – '+(m.ga??'—'):(m.time||'—');return `<article class="match-card${hasDailyPoster?' match-card--interactive':''}" data-match-id="${esc(m.id)}"><div class="match-competition">${m.provider==='espn'&&m.leagueId==='uefa.nations'?'<img class="match-league-badge" src="/home/assets/leagues/nations-league.png" alt="">':''}<span class="match-competition-copy">${esc(m.league)} <span>· ${esc(matchDay(m))}</span></span></div><div class="match-teams"><div><img src="${asset(m.homeLogo)}" alt=""><strong>${esc(m.home)}</strong></div><div class="match-center"><span>${esc(m.detailStatus||(live?'En cours':finished?'Terminé':'Coup d’envoi'))}</span><b>${esc(center)}</b>${live&&(m.detailClock||m.elapsed!=null)?`<small>${esc(m.detailClock||m.elapsed+'′')}</small>`:''}</div><div><img src="${asset(m.awayLogo)}" alt=""><strong>${esc(m.away)}</strong></div></div>${hasDailyPoster?`<button type="button" class="match-open" aria-label="Ouvrir la fiche du match : ${esc(m.home)} – ${esc(m.away)}" aria-haspopup="dialog" aria-controls="match-detail-dialog"><span>La fiche du match <b aria-hidden="true">↗</b></span></button>`:''}</article>`}
function renderMatches(){if(matchModalOpen)return;const focusId=document.activeElement?.closest('.match-card')?.dataset.matchId;const p=per(),pages=Math.max(1,Math.ceil(matches.length/p));mi=(mi+pages)%pages;document.querySelector('#mc-stage').innerHTML=matches.slice(mi*p,(mi+1)*p).map(matchCard).join('')||`<p>${matchFeedState==='loading'?'Chargement des matchs…':matchFeedState==='error'?'Les matchs sont momentanément indisponibles.':'Aucun match programmé prochainement'}</p>`;document.querySelector('#mc-dots').innerHTML=Array.from({length:pages},(_,i)=>`<button aria-label="Groupe de matchs ${i+1}" aria-pressed="${i===mi}" data-match-page="${i}"></button>`).join('');if(focusId)document.querySelector(`[data-match-id="${CSS.escape(focusId)}"] .match-open`)?.focus({preventScroll:true});}
document.querySelector('[data-match-prev]').onclick=()=>{mi--;renderMatches()};document.querySelector('[data-match-next]').onclick=()=>{mi++;renderMatches()};document.querySelector('#mc-dots').onclick=e=>{let b=e.target.closest('[data-match-page]');if(b){mi=+b.dataset.matchPage;renderMatches()}};document.querySelector('#match-pause').onclick=e=>{matchPaused=!matchPaused;e.target.textContent=matchPaused?'Reprendre':'Pause';e.target.setAttribute('aria-pressed',matchPaused)};setInterval(()=>{if(!window.TF_CAPTURE&&!matchPaused&&!matchModalOpen&&!document.hidden&&!document.querySelector('#match-center').matches(':hover,:focus-within')){mi++;renderMatches()}},10000);renderMatches();window.addEventListener('resize',renderMatches);if(matches[0])document.querySelector('#next-match').textContent='À suivre · '+matches[0].home+' – '+matches[0].away+' · '+matches[0].time;
window.TF_MATCH_CARDS={matches,render:renderMatches,setFeedState(value){matchFeedState=value;},setModalOpen(value){matchModalOpen=value;}};
const counts={};A.forEach(a=>{if(a.competition_id)counts[a.competition_id]=(counts[a.competition_id]||0)+1});let filter='all';
function renderArchives(){document.querySelector('#arch-chips').innerHTML=[['all','Toutes les compétitions',A.length],...Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([id,n])=>[id,C[id],n])].map(([id,label,n])=>`<button data-filter="${esc(id)}" aria-pressed="${filter===id}">${esc(label)} <span>${n}</span></button>`).join('');const arr=(filter==='all'?A:A.filter(a=>a.competition_id===filter)).slice(0,6);document.querySelector('#arch-out').innerHTML=arr.map((a,i)=>story(a,i===0?'major':i<3?'medium':'rest')).join('')||'<p>Aucun article publié dans cette compétition.</p>';}
document.querySelector('#arch-chips').onclick=e=>{let b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;renderArchives()}};document.querySelectorAll('[data-rubric]').forEach(el=>el.onclick=()=>{let c=D.competitions.find(c=>c.label_fr===el.dataset.rubric);filter=c?c.id:'all';renderArchives()});renderArchives();
// R03.20 : module documentaire autonome, sélection YouTube côté serveur.
const menu=document.querySelector('.menu-btn'),panel=document.querySelector('#menu-panel');menu.onclick=()=>{panel.hidden=!panel.hidden;menu.setAttribute('aria-expanded',!panel.hidden)};panel.querySelectorAll('a').forEach(a=>a.onclick=()=>{panel.hidden=true;menu.setAttribute('aria-expanded',false)});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.body.dataset.readingMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.mode===b.dataset.mode))});document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===(innerWidth<700?'smartphone':'desktop')));
document.querySelector('.rail-pause').onclick=e=>{const paused=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',paused);e.currentTarget.setAttribute('aria-label',paused?'Reprendre le bandeau':'Mettre le bandeau en pause');document.querySelector('.rail-track').style.animationPlayState=paused?'paused':'running'};
const dialog=document.querySelector('#game-choice');document.querySelector('[data-open-game-choice]').onclick=()=>dialog.showModal();document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};

window.TF_READY=true;
